site:
  title: Antora Docs For Demo
  start_page: ModuleA::example.adoc
content:
  sources:
  - url: https://github.com/gerometan/ModuleA.git
    version: '0.4.9'
  - url: https://github.com/gerometan/ModuleB.git
    branches: [main, feature_version]
    start_path: docs
ui:
  bundle:
    url: https://github.com/gerometan/antora-ui-bundle/raw/main/build/ui-bundle.zip

antora:
  extensions:
  - require: '@antora/lunr-extension'

    